services:

  #--- jenkinsBlue_moje ------------------------------------------------------------------------------------------------
  jenkins-docker-container:
    container_name: jenkins-docker-container
    image: jenkins-docker-image
    build:                                # https://jtreminio.com/blog/running-docker-containers-as-current-host-user/
      context: .                          # current dir as build context
      dockerfile: JenkinsDockerfile

    environment:
      - TERM=xterm-color

    restart: on-failure

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8080
