# docker compose up -d
# docker exec -it jenkins-docker-container cat var/jenkins_home/secrets/initialAdminPassword

services:

  #--- jenkinsBlue_moje ------------------------------------------------------------------------------------------------
  jenkins-docker-container:
    container_name: jenkins-docker-container
    image: jenkins-docker-image
    build:
      context: .
      dockerfile: JenkinsDockerfile

    environment:
      - TERM=xterm-color

    restart: on-failure

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8080
